"""Deterministic Pydantic v2 schemas for LeaseLens structured output.

These schemas enforce the exact JSON shape that the Antigravity agents
must produce, eliminating hallucinated formatting and guaranteeing
frontend compatibility.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    """Traffic-light risk classification."""
    LOW = "low"           # Green  — within standard market range
    MODERATE = "moderate" # Amber  — notable variance from baseline
    HIGH = "high"         # Red    — onerous/significantly deviating


class ClauseCategory(str, Enum):
    """CUAD-aligned clause categories for residential leases."""
    SECURITY_DEPOSIT = "Security Deposit"
    LOCK_IN_PERIOD = "Lock-in Period"
    NOTICE_PERIOD = "Notice Period"
    MAINTENANCE_LIABILITY = "Maintenance Liability"
    RENT_ESCALATION = "Rent Escalation"
    SUBLETTING = "Subletting"
    TERMINATION = "Termination"
    PAINTING_CHARGES = "Painting & Restoration Charges"
    UTILITIES = "Utilities & Common Area"
    OTHER = "Other"


class ClauseRisk(BaseModel):
    """Individual clause extraction with statistical deviation analysis.

    UPL GUARDRAIL: `educational_note` must NEVER contain legal advice,
    directives to sign/reject, or use words like 'illegal', 'void',
    'unenforceable', 'sue', or 'recommend'.
    """
    category: ClauseCategory = Field(
        description="The clause type from the CUAD-aligned taxonomy."
    )
    extracted_text: str = Field(
        description="Exact verbatim text extracted from the lease. No paraphrasing.",
        min_length=1,
    )
    market_standard: str = Field(
        description=(
            "The statistical regional baseline for this clause type, "
            "e.g., 'Standard security deposit: 2 months rent'."
        ),
    )
    deviation_percentage: float | None = Field(
        default=None,
        description=(
            "Quantified deviation from market standard as a percentage. "
            "Positive = above standard, Negative = below."
        ),
    )
    risk_level: RiskLevel = Field(
        description="Traffic-light risk classification based on statistical deviation."
    )
    educational_note: str = Field(
        description=(
            "A strictly non-advisory, informational explanation of the clause's "
            "mechanics and its statistical position relative to market norms. "
            "MUST NOT contain legal advice."
        ),
    )


class LeaseAnalysis(BaseModel):
    """Complete lease analysis output — the contract between agents and frontend."""
    document_title: str = Field(
        default="Untitled Lease Agreement",
        description="The title or identifier of the analyzed document.",
    )
    document_summary: str = Field(
        description=(
            "A brief, factual summary of the document parameters: "
            "parties, term, monthly rent, property address."
        ),
    )
    total_clauses_analyzed: int = Field(
        description="Total number of clauses identified and analyzed.",
        ge=0,
    )
    risks: list[ClauseRisk] = Field(
        default_factory=list,
        description="List of extracted clauses with risk assessments.",
    )
    overall_risk_score: float = Field(
        description=(
            "Aggregate risk score from 0.0 (fully standard) to 10.0 (highly onerous). "
            "Computed as weighted average of individual clause deviations."
        ),
        ge=0.0,
        le=10.0,
    )
    disclaimer: str = Field(
        default=(
            "This analysis is generated by an AI system for informational and "
            "educational purposes only. It does not constitute legal advice. "
            "Consult a qualified legal professional before making any decisions "
            "regarding this agreement."
        ),
        description="Mandatory legal disclaimer. Must always be present.",
    )
